<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class LoginValidation extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     * Валидность логина
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'login'=>'required',
            'password'=>'required'
        ];
    }
    public function messages()
    {
        return parent::messages()+
            [
                'login.required'=>'Поле логина обязательно для заполнения',
                'password.required'=>'Поле пароля обязательно для заполнения',
            ]; // TODO: Change the autogenerated stub
    }
}
