<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RegistrationValidation extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     * Валидность регистрации
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name'=>'required|regex:/^[АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя\s-]+$/',
            'surname'=>'required|regex:/^[АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя\s-]+$/',
            'patronymic'=>'nullable|regex:/^[АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюя\s-]+$/',
            'login'=>'required|regex:/^[A-Za-z0-9\s-]+$/|unique:users',
            'email'=>'required|email|unique:users',
            'password'=>'required|confirmed|min:6',
            'confirmation_polity'=>'required'
        ];
    }
    public function messages()
    {
        return parent::messages()+
            [
                'name.required'=>'Поле имени обязательно для заполнения',
                'surname.required'=>'Поле фамилии обязательно для заполнения',
                'patronymic.required'=>'Поле отчества обязательно для заполнения',
                'name.regex'=>'Разрешенные символы кириллица, пробел и тире',
                'surname.regex'=>'Разрешенные символы кириллица, пробел и тире',
                'patronymic.regex'=>'Разрешенные символы кириллица, пробел и тире',
                'email.required'=>'Поле почты обязательно для заполнения',
                'login.required'=>'Поле логина обязательно для заполнения',
                'password.required'=>'Поле пароля обязательно для заполнения',
                'password.min:6'=>'Поле пароля не может содержать меньше 6 символов',
                'confirmation_polity.required'=>'Вы должны согласиься для продолжения',
            ]; // TODO: Change the autogenerated stub
    }
}
